# Generated by Django 4.0.4 on 2022-05-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование')),
                ('supply_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('unit', models.CharField(choices=[('kg', 'Килограммы'), ('m', 'Метры'), ('pi', 'Штуки'), ('pa', 'Упаковки')], default='pi', max_length=2)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
