# Generated by Django 4.0.4 on 2022-05-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='common.supplier', verbose_name='Поставщик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='unit',
            field=models.CharField(choices=[('kg', 'Килограммы'), ('m', 'Метры'), ('pi', 'Штуки'), ('pa', 'Упаковки')], default='pi', max_length=2, verbose_name='Единицы измерения'),
        ),
    ]
