# Generated by Django 4.0.4 on 2022-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_supplier_alter_good_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
