# Generated by Django 4.0.4 on 2022-06-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('goods', '0003_good_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='categories.category', verbose_name='Категории'),
        ),
    ]
