# Generated by Django 4.0.4 on 2022-06-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('categories', '0001_initial'),
        ('goods', '0004_good_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='goods', to='categories.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='good',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='common.supplier', verbose_name='Поставщик'),
        ),
    ]
