# Generated by Django 4.0.4 on 2022-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_managers'),
        ('goods', '0007_alter_good_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='goods', to='categories.category', verbose_name='Категории'),
        ),
    ]
