# Generated by Django 4.0.4 on 2022-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('categories', '0002_category_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='site',
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='sites.site'),
            preserve_default=False,
        ),
    ]
