version: '3'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - '54322:5432'
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: IvanT
      POSTGRES_PASSWORD: qwaszx
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data

  backend:
    build:
      context: ./django_project
    privileged: true
    restart: always
    expose:
      - 8000
    command: bash -c "
      python manage.py migrate &&
      gunicorn django_project.wsgi -b 0.0.0.0:8000
      "

    environment:
      DJANGO_SETTINGS_MODULE: django_project.settings.prod
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - '8000:8000'
    depends_on:
      - backend
